### ISSUE TITLE
Barred imports case extra 

### ISSUE THREAD

**Issue by cgatian** [kreuzerk/import-conductor#23] opened 2020-08-24 13:35 UTC

**Comment by kreuzerk** [comment] 2020-08-24 13:44
Is this a duplicate of https://github.com/kreuzerk/import-conductor/issues/24?

**Comment by cgatian** [comment] 2020-08-24 13:59
Sorry about this.

**Closed** 2020-08-24 13:59 UTC

**Comment by kreuzerk** [comment] 2020-08-24 14:09
No worries - Thx for reporting the issues. 👍
